DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

SimpleBlog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.static import serve

from SimpleBlog.settings import MEDIA_ROOT
# from SimpleBlog.settings import STATIC_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('apps.blog.urls')),
    url(r'', include('apps.comment.urls')),
    # 配置上传文件的访问url
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),
    # 配置富文本ueditor的URL路径
    url(r'^ueditor/', include('DjangoUeditor.urls')),
]

apps/blog/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2020/3/25 17:46
# @Author  : Skylor Tang
# @Email   : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url, include
from apps.blog.views import IndexView, PostDetailView, ArchivesView, CategoryView, TagView

app_name = 'blog'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', PostDetailView.as_view(), name='post_detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<cate_id>[0-9]+)/$', CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>[0-9]+)/$', TagView.as_view(), name='tag'),
    # url(r'^search/$', views.search, name='search'),
]

apps/comment/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2020/3/25 17:46
# @Author  : Skylor Tang
# @Email   : 
# @File    : urls.py
# @Software: PyCharm


from django.conf.urls import url

from apps.comment.views import CommentView

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_id>[0-9]+)/$', CommentView.as_view(), name='post_comment'),
]

apps/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.html import strip_tags

from DjangoUeditor.models import UEditorField

from apps.users.models import BaseModel
from apps.users.models import BaseModel


UserProfile = get_user_model()


class Category(BaseModel):
    STATUS_ITEMS = (
        ('1', '正常'),
        ('0', '删除'),
    )

    name = models.CharField(max_length=50, verbose_name="名称")
    status = models.CharField(max_length=1, choices=STATUS_ITEMS, verbose_name="状态")
    is_nav = models.BooleanField(default=False, verbose_name="是否为导航")
    owner = models.ForeignKey(UserProfile, verbose_name="作者", on_delete=models.CASCADE)

    class Meta:
        verbose_name = verbose_name_plural = '分类'

    # 设置模型的返回值
    def __str__(self):
        return self.name


class Tag(BaseModel):
    STATUS_ITEMS = (
        ('1', '正常'),
        ('0', '删除'),
    )

    name = models.CharField(max_length=10, verbose_name="名称")
    status = models.CharField(max_length=1, choices=STATUS_ITEMS, verbose_name="状态")
    owner = models.ForeignKey(UserProfile, verbose_name="作者", on_delete=models.CASCADE)

    class Meta:
        verbose_name = verbose_name_plural = '标签'
        ordering = ['-id']

    def __str__(self):
        return self.name


class Post(BaseModel):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_DRAFT = 2
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
        (STATUS_DRAFT, '草稿'),
    )

    title = models.CharField(max_length=255, verbose_name="标题")
    desc = models.CharField(max_length=1024, blank=True, verbose_name="摘要")
    content = UEditorField(verbose_name="正文", width=600, height=300, imagePath="post/ueditor/images/",
                          filePath="post/ueditor/files/", default="")
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name="状态")
    category = models.ForeignKey(Category, verbose_name="分类", on_delete=models.DO_NOTHING)
    tag = models.ManyToManyField(Tag, verbose_name="标签")
    owner = models.ForeignKey(UserProfile, verbose_name="作者", on_delete=models.CASCADE)

    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0, verbose_name="阅读量")
    # 新增 comments 评论量

    pv = models.PositiveIntegerField(default=1)
    uv = models.PositiveIntegerField(default=1)

    # def get_absolute_url(self):
    #     return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = verbose_name_plural = "文章"
        ordering = ['-add_time', 'title']

    def __str__(self):
        return self.title

    # def increase_views(self):
    #     self.views += 1
    #     self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        # 如果没有填写摘要，摘取前54个字符
        if not self.desc:
            self.desc = strip_tags(self.content)[:54]+'...'
        super().save(*args, **kwargs)

apps/comment/models.py
from django.db import models
from apps.blog.models import Post
from apps.users.models import BaseModel
# Create your models here.


class Comment(BaseModel):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="博客文章")
    content = models.CharField(max_length=2000, verbose_name="内容")
    nickname = models.CharField(max_length=50, verbose_name="昵称")
    website = models.URLField(verbose_name="网站")
    email = models.EmailField(verbose_name="邮箱")
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name="状态")

    class Meta:
        verbose_name = verbose_name_plural = "评论"
        ordering = ['-add_time']

    def __str__(self):
        return self.nickname

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
{% load blog_tags %}
<head>
    <title>{% block title %}Black &amp; White{% endblock %}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block blog_css %}
        <!--此处放置其他页面各自的可能会导入的css文件-->
    {% endblock %}

    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
    {% block blog_js %}
        <!--此处放置其他页面各自的可能会导入的js文件-->
    {% endblock %}
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>


{% block content-body %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    {% block main %}
                    {% endblock main %}
                </main>
                <aside class="col-md-4">
                    {% block catalog %}
                    {% endblock catalog %}
                    <div class="widget widget-recent-posts">
                        <h3 class="widget-title">最新文章</h3>
                        {% get_recent_posts as recent_post_list %}
                        <ul>
                            {% for post in recent_post_list %}
                                <li>
                                    <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
                                </li>
                            {% empty %}
                                暂无文章！
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="widget widget-archives">
                        <h3 class="widget-title">归档</h3>
                        {% archives as date_list %}
                        <ul>
                            {% for date in date_list %}
                                <li>
                                    <a href="{% url 'blog:archives' date.year date.month %}">
                                        {{ date.year }} 年 {{ date.month }} 月</a>
                                </li>
                            {% empty %}
                                暂无归档！
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-category">
                        <h3 class="widget-title">分类</h3>
                        {% get_categories as category_list %}
                        <ul>
                            {% for category in category_list %}
                                <li>
                                    <a href="{% url 'blog:category' category.id %}">
                                        {{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
                                </li>
                            {% empty %}
                                暂无分类！
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title">标签云</h3>
                        {% get_tags as tag_list %}
                              <ul>
                                {% for tag in tag_list %}
                                <li>
                                    <a href="{% url 'blog:tag' tag.id %}">{{ tag.name }}</a>
                                </li>
                                {% empty %}
                                暂无标签！
                                {% endfor %}
                              </ul>
                    </div>
                    <div class="rss">
                        <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    </div>
                </aside>
            </div>
        </div>
    </div>
{% endblock %}

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2020 - 2021<a href="#" target="_blank" title=""></a>
                    <a href="https://github.com/Skylor-Tang" title="网页模板" target="_blank">唐美健</a>的博客 Powered by Django

            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="{% url 'blog:index' %}">博客</a></li>
            <li><a href="#">关于</a></li>
            <li><a href="#">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
{% for post in all_posts.object_list %}
    <article class="post post-{{ forloop.counter }}">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.add_time }}">{{ post.add_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.owner }}</a></span>
                <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ post.desc }}</p>
            <div class="read-more cl-effect-14">
                <a href="{% url 'blog:post_detail' post.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
{% endfor %}
    <div class="pagination">
        <ul class="pagelist">
            {% if all_posts.has_previous %}
                <li class="long"><a href="?{{ all_posts.previous_page_number.querystring }}">上一页</a></li>
            {% endif %}

            {% for page in all_posts.pages %}
                {% if page %}
                    {% ifequal page all_posts.number %}
                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% else %}
                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                    {% endifequal %}
                {% else %}
                    <li class="none">...</li>
                {% endif %}
            {% endfor %}
            {% if all_posts.has_next %}
                <li class="long"><a href="?{{ all_posts.next_page_number.querystring }}">下一页</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

templates/single.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}

    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.add_time }}">{{ post.add_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.owner }}</a></span>
                <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {% autoescape off %}{{ post.content }}{% endautoescape %}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.id %}" method="post" class="comment-form">
            <div class="row">
                <div class="col-md-4">
                    <label for="id_name">昵称：</label>
                    <input type="text" id="id_name" name="nickname" required>
                </div>
                <div class="col-md-4">
                    <label for="id_email">邮箱：</label>
                    <input type="email" id="id_email" name="email" required>
                </div>
                <div class="col-md-4">
                    <label for="id_url">网址：</label>
                    <input type="text" id="id_url" name="website">
                </div>
                <div class="col-md-12">
                    <label for="id_comment">评论：</label>
                    <textarea name="content" id="id_comment" required></textarea>
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
            {% csrf_token %}
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ comment_list.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="nickname">{{ comment.nickname }}</span>
                    <time class="submit-date" datetime="{{ comment.add_time }}">{{ comment.add_time }}</time>
                    <div class="text">
                        {{ comment.content }}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </section>
    {% block catalog %}

    {% endblock %}
{% endblock %}